server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
      default-filters:
        -
      globalcors:
        add-to-simple-url-handler-mapping: true  #cors方案，由浏览器询问服务器是否允许跨域 放行本次options询问请求
        cors-configurations:
          '[/**]':  #拦截一切请求 进行跨域处理
            allowedOrigins:
              - "http://localhost:8090"
            allowedMethods:
              - "GET"
              - "POST"
              - "OPTIONS"
              - "DELETE"
              - "PUT"
            allowedHeaders: "*"
            allowedCredentials: true # 跨域是否允许携带cookie
            maxAge: 360000 #跨域有效期  毫秒  避免频繁请求浪费性能
