server:
  port: 8086
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8088/eureka/

service:
  name:
    user: http://user-service/user/queryUser

mybatis:
  configuration:
    map-underscore-to-camel-case: true